### ISSUE TITLE
Error calling R from python in order to use a Seurat object in Scanpy

### ISSUE THREAD

**Issue by swokybio** [LuckyMD/Code_snippets#1]
Hi, 

I am trying to run your code to perform a trajectory analysis using scanpy on my pre-processed object created in Seurat but I am having trouble calling R using python.

I used 'jupyter nbconvert --to script' to extract your code from jupyter notebook, and I am now using ipython to execute my script. 

When I run my script I get a 'Segmentation fault'. Any thoughts on what I am doing wrong?

```
import sys 
sys.settrace
import scanpy as sc
import numpy as np
import anndata2ri
import rpy2
print(rpy2.__version__)
import rpy2.robjects as robjects
import rpy2.robjects.packages as rpackages
from rpy2.robjects.vectors import StrVector

# Activate the anndata2ri conversion between SingleCellExperiment and AnnData
anndata2ri.activate()

#This runs R code in jupyter notebook cells
get_ipython().run_line_magic('load_ext', 'rpy2.ipython')

sc.settings.verbosity = 3 
sc.logging.print_versions()

get_ipython().run_cell_magic('R', '', 'suppressPackageStartupMessages(library(Seurat))\n\n# Loaddataset from Seurat tutorial\nload(file="/storage/htc/lucylab/single_cell_seq/Seurat/New_QC_data.RData")')
```

**Comment by LuckyMD** [comment]
Hey!
This issue would probably best be posted on the [anndata2ri github](https://github.com/theislab/anndata2ri).

It would make this a lot easier to debug if you ran this line-by-line in a jupyter notebook to see where the error comes up. 

Also, what version of `rpy2` are you running and have you linked R with your ipython session via `IRKernel`?

I’m also a little confused by the random `sys.settrace` line without calling the function.

I have not run R magics in a script like this before, so i can’t say if this should work. Typically using anndata2ri in a script would involve calling rpy2 and anndata2ri directly to call R functions.

**Comment by fidelram** [comment]
Hi, I also had a similar problem. This is related to Seurat latest version. Seurat version 3.0.2 works for me.

**Comment by LuckyMD** [comment]
Thanks @fidelram! I've been using Seurat 3.0.2 and 2.3.4 with `anndata2ri` and it's been working well so far.

**Comment by fidelram** [comment]
Some other people is having the same problem. See https://github.com/satijalab/seurat/issues/2079

**Comment by LuckyMD** [comment]
It's too bad that this is not something they're looking to address.

**Comment by swokybio** [comment]
Thanks @fidelram!!

**Comment by LuckyMD** [comment]
A further aspect of this seems to be the R version... R 3.5.1 seems to work with Seurat 3.1.1.

I'll close this for now, as I guess this would need to be fixed on the Seurat side.

**Comment by PNorvaisas** [comment]
Instead of loading the whole `Seurat` library via r2py package just execute the function you need. Here `adata` is an `AnnData` object:
```python
import rpy2.robjects as ro
import anndata2ri

anndata2ri.activate()

ro.globalenv["adata"] = adata
ro.r(
    'seurat_obj <- Seurat::as.Seurat(adata, counts="X", cells="obs", features="var", data = NULL)'
)

ro.r(
    "res <- Seurat::SCTransform(object=seurat_obj, \
    return.only.var.genes = FALSE,\
    do.correct.umi = FALSE)"
)
```
It worked for me with `SCTransform` and the most recent Seurat (3.1.4).
