### ISSUE TITLE
having trouble when conducting "%%R  library(Seurat)"

### ISSUE THREAD

**Issue by daisyyr** [LuckyMD/Code_snippets#2]
Hi~Thanks for your seurat to scanpy tutorial!
I'm using jupyter notebook of Linux server.
I'm having trouble when conducting 

%%R 
library(Seurat)

the notebook process just shutdown and restarted automatically. I've tried many times and I
still got the same problem.
Is there any possible reason for this? I'm not very familiar with python so I really need some suggestions.
Many Thanks!!!

**Comment by daisyyr** [comment]
I have solved the problem which might be due to the version of Seurat.
I changed from Seurat v3.1.0 to Seurat v3.0.2.
devtools::install_github(repo = 'satijalab/seurat@v3.0.2', dependencies=FALSE, force=TRUE)
And it worked.

**Comment by LuckyMD** [comment]
Hi,

Thanks for reporting the issue and pointing out how to fix it quickly. I haven't tested v3.1.0 yet tbh, however suddenly shutting down sounds more like a system issue. Maybe take a look at the jupyter notebook logging. It seems like some kernel panic.

**Comment by Momomocheng** [comment]
devtools::install_github(repo = 'satijalab/seurat@v3.0.2', dependencies=FALSE, force=TRUE)
works for me, and the seurat v4.0 has the same problem!

**Comment by LuckyMD** [comment]
So it seems that Seurat v4 is not even loadable in the environment? This is probably a dependency issue, rather than a Seurat issue. As Seurat is quite widely used... it seems very unlikely that this would not be compatible with the jupyter IRkernel
