### ISSUE TITLE
final conversino doesn't work

### ISSUE THREAD

**Issue by tkkanno** [LuckyMD/Code_snippets#3]
thanks for making this tool! i'm stuck at the final step where the R object is not converted to python:

![Screen Shot 2020-02-11 at 4 59 38 PM](https://user-images.githubusercontent.com/7226376/74283478-ed477780-4cef-11ea-8381-3e8387897046.png)

any tips?

**Comment by tkkanno** [comment]
i had an error in my screenshot, but here is a correct version
![Screen Shot 2020-02-11 at 5 03 28 PM](https://user-images.githubusercontent.com/7226376/74283781-7d85bc80-4cf0-11ea-882d-667ccc452905.png)

**Comment by tkkanno** [comment]
I fixed this issue by adding a line of code

'test = %R pbmc_scan'

now i have an anndata object working in python

**Comment by LuckyMD** [comment]
Hey!

You solved this a lot quicker than I could respond it seems ;). Glad it's working for you now. I have the feeling that you shouldn't need that last line of code though. Maybe you could separate the cell where you do `pbmc_scan <- as.SingleCellExperiment(pbmc)` from the cell where you output the object to python. So something like this:

```
[33]: %%R
      pbmc_scan <- as.SingleCellExperiment(pbmc)
[34]: %%R -o pbmc_scan
      pbmc_scan
[35]: pbmc_scan
```

My feeling says that should work.
