### ISSUE TITLE
Error occurs in as.SingleCellExperiment step

### ISSUE THREAD

**Issue by ShaowenJ** [LuckyMD/Code_snippets#5]
The previous steps work totally fine, I think.
But an error occurs in the as.SingleCellExperiment(obj) step:
R[write to console]: Error in if (assay.used %in% SingleCellExperiment::altExpNames(x = sce) &  : 
  argument is of length zero

![image](https://user-images.githubusercontent.com/30546732/135408892-657cd1c1-53d0-4bd0-b807-fe4b370a11d9.png)

![image](https://user-images.githubusercontent.com/30546732/135409042-0bc34456-3515-43e4-b013-236c0ac4da21.png)

Any solutions???
Thanks!

**Comment by LuckyMD** [comment]
Hey! This looks like an issue in Seurat to be honest. Could you check the output of `str(obj)` and `class(obj)` just to make sure you actually have a `SingleCellExperiment` object? Also, which versions of Seurat and SingleCellExperiment do you have?

**Comment by ShaowenJ** [comment]
Thanks for the quick response, yes, it is a Seurat issue since I ran into the same error in Rstudio.
Seurat_4.0.3 SingleCellExperiment_1.12.0

the output of str(obj)

Formal class 'Seurat' [package "SeuratObject"] with 13 slots
  ..@ assays      :List of 1
  .. ..$ RNA:Formal class 'Assay' [package "Seurat"] with 8 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:71381153] 15 16 74 75 89 116 192 264 633 758 ...
  .. .. .. .. .. ..@ p       : int [1:42596] 0 1502 3010 4068 5058 6279 8800 9906 11582 13486 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 25242 42595
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:25242] "A1BG" "A1BG-AS1" "A2M" "A2M-AS1" ...
  .. .. .. .. .. .. ..$ : chr [1:42595] "AAACGGGTCCCTTGCA_LUNG_N19" "AAAGTAGAGAGTACAT_LUNG_N19" "AACACGTTCTGTACGA_LUNG_N28" "AACCATGGTAAGGGAA_LUNG_N34" ...
  .. .. .. .. .. ..@ x       : num [1:71381153] 2 1 1 1 1 1 1 1 1 1 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:71381153] 15 16 74 75 89 116 192 264 633 758 ...
  .. .. .. .. .. ..@ p       : int [1:42596] 0 1502 3010 4068 5058 6279 8800 9906 11582 13486 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 25242 42595
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:25242] "A1BG" "A1BG-AS1" "A2M" "A2M-AS1" ...
  .. .. .. .. .. .. ..$ : chr [1:42595] "AAACGGGTCCCTTGCA_LUNG_N19" "AAAGTAGAGAGTACAT_LUNG_N19" "AACACGTTCTGTACGA_LUNG_N28" "AACCATGGTAAGGGAA_LUNG_N34" ...
  .. .. .. .. .. ..@ x       : num [1:71381153] 1.3 0.85 0.85 0.85 0.85 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num[0 , 0 ] 
  .. .. .. ..@ key          : chr "rna_"
  .. .. .. ..@ assay.orig   : NULL
  .. .. .. ..@ var.features : chr(0) 
  .. .. .. ..@ meta.features:'data.frame':	25242 obs. of  0 variables
  .. .. .. ..@ misc         : NULL
  ..@ meta.data   :'data.frame':	42595 obs. of  14 variables:
  .. ..$ orig.ident              : Factor w/ 1 level "NSCLC_GSE131907": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ nCount_RNA              : num [1:42595] 7459 6898 4865 4103 3064 ...
  .. ..$ nFeature_RNA            : int [1:42595] 1502 1508 1058 990 1221 2521 1106 1676 1904 732 ...
  .. ..$ UMAP_1                  : num [1:42595] -5.923 1.782 -0.301 0.748 1.095 ...
  .. ..$ UMAP_2                  : num [1:42595] 2.43 11.461 3.04 11.176 0.926 ...
  .. ..$ Celltype..malignancy.   : Factor w/ 3 levels "Immune cells",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ Celltype..major.lineage.: Factor w/ 12 levels "B","CD4Tconv",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ Celltype..minor.lineage.: Factor w/ 15 levels "B","CD4Tn","CD8Tcm",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ seurat_clusters         : int [1:42595] 2 2 2 2 2 2 2 2 2 2 ...
  .. ..$ Sample                  : Factor w/ 58 levels "BRONCHO_11","BRONCHO_58",..: 32 32 34 37 32 34 29 34 27 33 ...
  .. ..$ TNMstage                : Factor w/ 4 levels " I"," II"," III",..: 1 1 3 1 1 3 1 3 1 1 ...
  .. ..$ Patient                 : Factor w/ 44 levels "P0001","P0006",..: 6 6 9 12 6 9 3 9 1 7 ...
  .. ..$ Source                  : Factor w/ 6 levels "mBrain","mLN",..: 4 4 6 6 4 6 4 6 4 6 ...
  .. ..$ Stage                   : Factor w/ 2 levels "Metastatic","Primary": 2 2 2 2 2 2 2 2 2 2 ...
  ..@ active.assay: chr "RNA"
  ..@ active.ident: Factor w/ 21 levels "2","0","1","18",..: 1 1 1 1 1 1 1 1 1 1 ...
  .. ..- attr(*, "names")= chr [1:42595] "AAACGGGTCCCTTGCA_LUNG_N19" "AAAGTAGAGAGTACAT_LUNG_N19" "AACACGTTCTGTACGA_LUNG_N28" "AACCATGGTAAGGGAA_LUNG_N34" ...
  ..@ graphs      : list()
  ..@ neighbors   : list()
  ..@ reductions  :List of 1
  .. ..$ umap:Formal class 'DimReduc' [package "SeuratObject"] with 9 slots
  .. .. .. ..@ cell.embeddings           : num [1:42595, 1:2] -5.923 1.782 -0.301 0.748 1.095 ...
  .. .. .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. .. .. ..$ : chr [1:42595] "AAACGGGTCCCTTGCA_LUNG_N19" "AAAGTAGAGAGTACAT_LUNG_N19" "AACACGTTCTGTACGA_LUNG_N28" "AACCATGGTAAGGGAA_LUNG_N34" ...
  .. .. .. .. .. ..$ : chr [1:2] "UMAP_1" "UMAP_2"
  .. .. .. ..@ feature.loadings          : num[0 , 0 ] 
  .. .. .. ..@ feature.loadings.projected: num[0 , 0 ] 
  .. .. .. ..@ assay.used                : chr(0) 
  .. .. .. ..@ global                    : logi TRUE
  .. .. .. ..@ stdev                     : num(0) 
  .. .. .. ..@ key                       : chr "UMAP_"
  .. .. .. ..@ jackstraw                 :Formal class 'JackStrawData' [package "SeuratObject"] with 4 slots
  .. .. .. .. .. ..@ empirical.p.values     : num[0 , 0 ] 
  .. .. .. .. .. ..@ fake.reduction.scores  : num[0 , 0 ] 
  .. .. .. .. .. ..@ empirical.p.values.full: num[0 , 0 ] 
  .. .. .. .. .. ..@ overall.p.values       : num[0 , 0 ] 
  .. .. .. ..@ misc                      : list()
  ..@ images      : list()
  ..@ project.name: chr "NSCLC_GSE131907"
  ..@ misc        : list()
  ..@ version     :Classes 'package_version', 'numeric_version'  hidden list of 1
  .. ..$ : int [1:3] 3 2 2
  ..@ commands    : list()
  ..@ tools       : list()

I think this is a Seurat object, what is a SingleCellExperiment object? Do Seurat objects belong to that?

**Comment by LuckyMD** [comment]
Ah, sorry, you're going back to AnnData from Seurat here. Ofc it's a Seurat object. I think you'd have to ask this question on the Seurat github. They will be better able to support you for their own function.

**Comment by ShaowenJ** [comment]
Hi @LuckyMD Sorry for bringing this up again.
I re-create the seurat object with its original count matrix, and this time it works fine in my Rstudio, but failed in this pipeline.
```{r}
library(Seurat)
library(SeuratDisk)
files = list.files(".",".rds")
f = files[2]
obj = readRDS(f)
meta = obj@meta.data
ct = as.matrix(obj@assays$RNA@counts)
sce = CreateSeuratObject(ct,min.cells = 0,min.features = 0,meta.data = meta)
obj_sce = as.SingleCellExperiment(x = sce,assay = "RNA")
```
output: 
> obj_sce
class: SingleCellExperiment 
dim: 25242 42595 
metadata(0):
assays(2): counts logcounts
rownames(25242): A1BG A1BG-AS1 ... bP-21264C1.2 bP-2189O9.3
rowData names(0):
colnames(42595): AAACGGGTCCCTTGCA_LUNG_N19 AAAGTAGAGAGTACAT_LUNG_N19 ... TTTGCGCGTTAAGATG_LUNG_N09
  TTTGCGCTCTCTGAGA_LUNG_N09
colData names(15): orig.ident nCount_RNA ... Stage ident
reducedDimNames(0):
altExpNames(0):

output in jupyter notebook
![image](https://user-images.githubusercontent.com/30546732/136525575-288f825b-22f0-458b-a612-e5340104f803.png)

**Same library version
SingleCellExperiment_1.12.0
Seurat_4.0.4**

Thanks!

**Comment by ShaowenJ** [comment]
I realized I could use SeuratData in R to convert to h5ad
