### ISSUE TITLE
Import old Seurat object into R and into scanpy

### ISSUE THREAD

**Issue by kristianunger** [LuckyMD/Code_snippets#6]
Based on the code you provide in Seurat_to_anndata.ipynb I am trying to import a "old Seurat object" into scanpy. 

Doing `%%R
suppressPackageStartupMessages(library(Seurat))
#.libPaths()
load("tissue.rdata") #tissue old Seurat object
refset <- CreateSeuratObject(counts = tissue@raw.data, meta.data = tissue@meta.data, project = 'human_dat', min.cells = 3, min.features = 200)

refset`

works well but when I then try to do `%%R
#convert the Seurat object to a SingleCellExperiment object
refset_sce <- as.SingleCellExperiment(refset)

refset_sce`

I get the errors:

"R[write to console]: Error in validObject(.Object) : 
  invalid class “dgCMatrix” object: 1: invalid object for slot "i" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 2: invalid object for slot "p" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 3: invalid object for slot "Dim" in class "dgCMatrix": got class "array", should be or extend class "integer"
invalid class “dgCMatrix” object: 4: invalid object for slot "x" in class "dgCMatrix": got class "array", should be or extend class "numeric"
"

Would you know how to fix this?

Best

Kristian

**Comment by kristianunger** [comment]
found a solution by going another route: export of Seurat object to h5ad anndata file using https://github.com/cellgeni/sceasy and then easily reading into scanpy using sc.read_h5ad.

**Comment by LuckyMD** [comment]
Hey! This looks like an issue with the latest `rpy2` version. Check the issue here:
https://github.com/theislab/anndata2ri/issues/63

If you downgrade to below version 3.4.3 things should work.

**Comment by kristianunger** [comment]
Thanks for this!
